In [1]:
import cv2

In [3]:
img = cv2.imread("img1.jpg")  #image read
cv2.imshow("willmajeet",img)   # image show
cv2.waitKey(10000)      #  image frame wait   time - ms  and  0 pass keyboard any key press
cv2.destroyAllWindows()   # all windows close
# cv2.destroyWindow()     # only one window close

In [4]:
img = cv2.imread("img1.jpg")  #image read
cv2.imshow("willmajeet",img)# image show
cv2.imshow("willmajeet1",img)# image show
cv2.waitKey(10000)      #  image frame wait   time - ms  and  0 pass keyboard any key press
cv2.destroyAllWindows()   # all windows close
# cv2.destroyWindow()     # only one window close

In [7]:
import numpy as np

In [9]:
img = cv2.imread(r"C:\Users\HP LAPTOP-PC\Desktop\DRDO Project\img5.jpg")  #image read
cv2.imshow("willmajeet",img)   # image show
cv2.waitKey(10000)      #  image frame wait   time - ms  and  0 pass keyboard any key press
cv2.destroyAllWindows()   # all windows close
# cv2.destroyWindow()     # only one window close

In [10]:
img = cv2.imread(r"C:\Users\HP LAPTOP-PC\Desktop\DRDO Project\img5.jpg")  #image read
re_img = cv2.resize(img,(500,600))
cv2.imshow("willmajeet",re_img)   # image show
cv2.waitKey(10000)      #  image frame wait   time - ms  and  0 pass keyboard any key press
cv2.destroyAllWindows()   # all windows close
# cv2.destroyWindow()     # only one window close

In [12]:
img = cv2.imread("img1.jpg")      # bgr  (0-255,0-255,0-255)
print(img)
print(img.shape)

[[[186 194 211]
  [186 194 211]
  [186 194 211]
  ...
  [186 194 211]
  [186 194 211]
  [186 194 211]]

 [[186 194 211]
  [186 194 211]
  [186 194 211]
  ...
  [186 194 211]
  [186 194 211]
  [186 194 211]]

 [[186 194 211]
  [186 194 211]
  [186 194 211]
  ...
  [186 194 211]
  [186 194 211]
  [186 194 211]]

 ...

 [[186 195 209]
  [186 195 209]
  [186 194 211]
  ...
  [186 194 211]
  [186 194 211]
  [186 194 211]]

 [[186 195 209]
  [186 195 209]
  [186 194 211]
  ...
  [186 194 211]
  [186 194 211]
  [186 194 211]]

 [[186 195 209]
  [186 195 209]
  [186 194 211]
  ...
  [186 194 211]
  [186 194 211]
  [186 194 211]]]
(524, 400, 3)


In [15]:
img = cv2.imread("img1.jpg",0)  #image read
re_img = cv2.resize(img,(500,500))
cv2.imshow("willmajeet",re_img) 
cv2.waitKey(0)      #  image frame wait   time - ms  and  0 pass keyboard any key press
cv2.destroyAllWindows()   # all windows close
# cv2.destroyWindow()     # only one window close

In [17]:
img = cv2.imread("img1.jpg",0)  #image read
print(img.shape)
img = cv2.resize(img,(500,600))
cv2.imshow("willmajeet",img) 
cv2.waitKey(0)      #  image frame wait   time - ms  and  0 pass keyboard any key press
cv2.destroyAllWindows()   # all windows close
# cv2.destroyWindow()     # only one window close

(524, 400)


In [19]:
img_get = cv2.imread(r"D:\Downloads\img3.jpg")  #image read
img_get = cv2.resize(img_get,(500,600))

txt = cv2.putText(img = img_get,
text = "SMRITI",
org = (50,80),
fontFace = cv2.FONT_HERSHEY_TRIPLEX,
fontScale = 2,
color = (255,0,0),
thickness = 3,
lineType = cv2.LINE_8,
bottomLeftOrigin = False)

txt = cv2.putText(img = img_get,
text = "SMRITI",
org = (50,80),
fontFace = cv2.FONT_HERSHEY_TRIPLEX,
fontScale = 2,
color = (0,0,255),
thickness = 3,
lineType = cv2.LINE_8,
bottomLeftOrigin = True)



cv2.imshow("willmajeet",img_get)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [21]:
def willma(x):
    pass   # funct. which take null value.

In [25]:
# color picker

img =np.zeros((500,500,3),np.uint8)*255
cv2.namedWindow("colour")  # add window  over image.

cv2.createTrackbar("R","colour",0,255,willma)
cv2.createTrackbar("G","colour",0,255,willma)
cv2.createTrackbar("B","colour",0,255,willma)

while True:
    cv2.imshow("colour",img)
    if cv2.waitKey(1) & 0xff == ord("q"):
        break
    r = cv2.getTrackbarPos("R","colour") # to get different colour to the trackbar.
    g = cv2.getTrackbarPos("G","colour")
    b = cv2.getTrackbarPos("B","colour")

    img[:] =[b,g,r]  # to bgr from rgb


cv2.destroyAllWindows()


In [27]:
def willma(x):
    pass

In [29]:
# getTrackBarpost[] function in opencv

img = np.zeros((500,500,3),np.uint8)
cv2.namedWindow("bar")
cv2.createTrackbar("on","bar",0,100,willma)
while True:
    cv2.imshow("bar",img)
    if cv2.waitKey(1) & 0xff == ord("p"):
        break
    on = cv2.getTrackbarPos("on","bar")
    print(on)
    img[:] = [0,0,on]

cv2.destroyAllWindows()

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
3
4
5
7
9
10
11
12
12
12
12
12
13
13
13
15
16
16
16
16
17
17
17
18
18
18
19
20
20
22
24
24
27
29
29
30
30
31
31
31
33
34
35
36
37
37
37
38
38
38
38
38
38
38
38
38
39
40
40
41
41
41
41
41
43
44
45
46
46


error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window_w32.cpp:2561: error: (-27:Null pointer) NULL window: 'bar' in function 'cvGetTrackbarPos'


In [31]:
# filter colour with opencv( live object filter)
cap = cv2.VideoCapture(0)
def willma(x):
    pass

cv2.namedWindow("demo")
cv2.createTrackbar("lb","demo",0,255,willma)
cv2.createTrackbar("lg","demo",0,255,willma)
cv2.createTrackbar("lr","demo",0,255,willma)

cv2.createTrackbar("ub","demo",255,255,willma)
cv2.createTrackbar("ug","demo",255,255,willma)
cv2.createTrackbar("ur","demo",255,255,willma)

while cap.isOpened():
        r,frame = cap.read()

        if r == True:
                img = cv2.resize(frame,(400,300))
                hsv_img = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

                Lb = cv2.getTrackbarPos("lb","demo")
                Lg = cv2.getTrackbarPos("lg","demo")
                Lr = cv2.getTrackbarPos("lr","demo")

                Ub = cv2.getTrackbarPos("ub","demo")
                Ug = cv2.getTrackbarPos("ug","demo")
                Ur = cv2.getTrackbarPos("ur","demo")

                lo = np.array([Lb,Lg,Lr])
                up = np.array([Ub,Ug,Ur])

                masks = cv2.inRange(hsv_img,lo,up)

                res = cv2.bitwise_and(img,img,mask = masks)

                cv2.imshow("res",res)
                cv2.imshow("mask",masks)
                cv2.imshow("hsv",hsv_img)
                cv2.imshow("willma",img)
                if cv2.waitKey(1)  & 0xff == ord("q"):
                    break
        else:
            break
cap.release()
cv2.destroyAllWindows()










In [33]:
# image contours using opencv ( build lines over images)

img = cv2.imread("Chrome-Logo.png")
img = cv2.resize(img,(600,500))

img1 = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

r,thr = cv2.threshold(img1,240,255,cv2.THRESH_BINARY)
contour,hex = cv2.findContours(thr,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
print(contour) # points which make contour line  # contour index

new_img = cv2.drawContours(img,contour,-1,(255,0,0),2)
cv2.imshow("wc1",new_img)
# cv2.imshow("wc",thr)
# cv2.imshow("willmajeet",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(array([[[293, 135]],

       [[292, 136]],

       [[288, 136]],

       [[287, 137]],

       [[284, 137]],

       [[283, 138]],

       [[281, 138]],

       [[280, 139]],

       [[279, 139]],

       [[278, 140]],

       [[276, 140]],

       [[275, 141]],

       [[274, 141]],

       [[273, 142]],

       [[272, 142]],

       [[270, 144]],

       [[269, 144]],

       [[267, 146]],

       [[266, 146]],

       [[264, 148]],

       [[263, 148]],

       [[250, 161]],

       [[250, 162]],

       [[247, 165]],

       [[247, 166]],

       [[245, 168]],

       [[245, 169]],

       [[243, 171]],

       [[243, 172]],

       [[242, 173]],

       [[242, 174]],

       [[240, 176]],

       [[240, 177]],

       [[239, 178]],

       [[239, 179]],

       [[238, 180]],

       [[238, 181]],

       [[237, 182]],

       [[237, 183]],

       [[236, 184]],

       [[236, 185]],

       [[235, 186]],

       [[235, 187]],

       [[234, 188]],

       [[234, 190]],

       [[