In [3]:
import cv2
import numpy as np

In [7]:
#background subtraction
org_v = cv2.VideoCapture(r"C:\Users\HP LAPTOP-PC\Pictures\Camera Roll\WIN_20240720_16_16_54_Pro.mp4")
sub_m = cv2.createBackgroundSubtractorMOG2()  # to subtract background
while True:
    r,frame = org_v.read()
    if r == True:
        frame = cv2.resize(frame,(700,500))
        sub_v = sub_m.apply(frame) # apply on current video
        cv2.imshow("willmajeet_sub",sub_v)
        cv2.imshow("willmajeet_org",frame)
        if cv2.waitKey(25) & 0xff == ord("p"):
            break
    else:
         break
org_v.release()
cv2.destroyAllWindows()
        

In [9]:
# extract images from video
org_v = cv2.VideoCapture(r"C:\Users\HP LAPTOP-PC\Desktop\moving person.mp4")
c = 0
while True:
    r,frame = org_v.read()
    if r == True:

        filename = "C://Users//HP LAPTOP-PC/Desktop//DRDO Project//images 30//org_img_"+str(c)+".png"
        cv2.imwrite(filename,frame) #to read and extract images from video.
        cv2.imshow("willmajeet_org",frame)
        c = c+1
        if cv2.waitKey(25) & 0xff == ord("p"):
            break
    else:
         break
org_v.release()
cv2.destroyAllWindows()

In [9]:
# cvtcolour method - to  change the colour space(basically img are in bgr format)
org = cv2.imread("img3.jpg")
org = cv2.resize(org,(500,500))

#new = cv2.cvtColor(org,cv2.COLOR_BGR2GRAY)  CHANGE THE COLOUR  TO SPACE
#new = cv2.cvtColor(org,cv2.COLOR_BGR2HSV) 
#new = cv2.cvtColor(org,cv2.COLOR_BGR2HLS)
new = cv2.cvtColor(org,cv2.COLOR_BGR2LUV)

cv2.imshow("org",org)
cv2.imshow("new",new)
cv2.waitKey(0)
cv2.destroyAllWindows()



In [11]:
#CROP THE IMAGE 

img = cv2.imread("img3.jpg")
img = cv2.resize(img,(500,600))

print(img.shape)
# img[y1:y2, x1:x2]

crop = img[:190,150:300] 

cv2.imshow("crop",crop)
cv2.imshow("willmajeet",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


(600, 500, 3)


In [66]:
# create blank image ( all white channel & all black channel)

img = cv2.imread("img1.jpg")
print(img.shape)



(524, 400, 3)


In [74]:
new_img = np.ones((500,500,3),np.uint8)*255    # for white channel
#print(new_img)            
cv2.imshow("willmajeet",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [72]:
new_img = np.zeros((500,500,3),np.uint8)*255  # for black channel
cv2.imshow("willmajeet",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [68]:
print(img)

[[[186 194 211]
  [186 194 211]
  [186 194 211]
  ...
  [186 194 211]
  [186 194 211]
  [186 194 211]]

 [[186 194 211]
  [186 194 211]
  [186 194 211]
  ...
  [186 194 211]
  [186 194 211]
  [186 194 211]]

 [[186 194 211]
  [186 194 211]
  [186 194 211]
  ...
  [186 194 211]
  [186 194 211]
  [186 194 211]]

 ...

 [[186 195 209]
  [186 195 209]
  [186 194 211]
  ...
  [186 194 211]
  [186 194 211]
  [186 194 211]]

 [[186 195 209]
  [186 195 209]
  [186 194 211]
  ...
  [186 194 211]
  [186 194 211]
  [186 194 211]]

 [[186 195 209]
  [186 195 209]
  [186 194 211]
  ...
  [186 194 211]
  [186 194 211]
  [186 194 211]]]


In [12]:
img = cv2.imread("img5.jpg")
img = cv2.resize(img,(700,500))

crop = img[34:187, 258:432] # 432-258=174+432=606
img[34:187, 432:606] = crop # right
img[34:187, 84:258] = crop   # left  (258-174)
  

cv2.imwrite("save.jpg",img)  # to save the resize img.
cv2.imshow("willmajeet",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [54]:
# img[y1:y2,x1:x2]
img = cv2.imread("save.jpg")


crop = img[34:187, 258:432]  # shortcut trick to get it by paint

cv2.imshow("willmajeet",crop)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# flip, rotate, transpose.

img = cv2.imread("img1.jpg")
img = cv2.resize(img,(500,500))

#img = cv2.flip(img,1) # y axis
#img = cv2.flip(img,0) # x axis
#img = cv2.flip(img,-1) # y,x axis

#img = cv2.rotate(img,cv2.ROTATE_180)
#img = cv2.rotate(img,cv2.ROTATE_90_CLOCKWISE)
#img = cv2.rotate(img,cv2.ROTATE_90_COUNTERCLOCKWISE)

img = cv2.transpose(img)

cv2.imshow("willmajeet",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [5]:
# saving a video.
cap = cv2.VideoCapture(0)

f = cv2.VideoWriter_fourcc(*"XVID") # to record normal like mp4,hd etc.video.
out = cv2.VideoWriter("willma1.mp4",f,20.0,(640,480),0)  # frame per second,pixel size.   to save the video. 0 FOR REMOVING ALL 3 COLOURS.
while cap.isOpened():
    r,frame = cap.read()
    if r == True:
        frame = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        frame = cv2.flip(frame,1)
        out.write(frame)
        cv2.imshow("willmajeet",frame)
        if cv2.waitKey(1) & 0xff == ord("p"):
            break
    else:
        break

cap.release()
out.release()
cv2.destroyAllWindows()

