In [1]:
import cv2
import numpy as np

In [1]:
# contour moments( provide proper info.about area on which contour is build)
#convex hull (tell min.contour ofthe object)

In [ ]:
# contour moment
img = cv2.imread("shap.jpg")

gry = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

_,thr = cv2.threshold(gry,205,255,cv2.THRESH_BINARY)

cnt,hir = cv2.findContours(thr,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)  # TO FIND THE CONTOUR

#img = cv2.drawContours(img,cnt,-1,(0,0,255),4)  # to apply contour on current image

ar = []
for c in cnt:
    m = cv2.moments(c)
    x = int(m["m10"]/m["m00"])
    y = int(m["m01"]/m["m00"])
    cv2.drawContours(img,cnt,-1,(0,0,255),4)
    cv2.circle(img,(x,y),5,(255,0,0),-1)
    a = cv2.contourArea(c)
    ar.append(a)
print(ar)
cv2.imshow("thre",thr)
cv2.imshow("willma",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
# convex hull

img = cv2.imread("shap.jpg")

gry = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

_,thr = cv2.threshold(gry,205,255,cv2.THRESH_BINARY)

cnt,hir = cv2.findContours(thr,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)  # TO FIND THE CONTOUR

#img = cv2.drawContours(img,cnt,-1,(0,0,255),4)  # to apply contour on current image

ar = []
for c in cnt:
    m = cv2.moments(c)
    x = int(m["m10"]/m["m00"])
    y = int(m["m01"]/m["m00"])
    cv2.drawContours(img,cnt,-1,(0,0,255),4)
    cv2.circle(img,(x,y),5,(255,0,0),-1)
    a = cv2.contourArea(c)
    ar.append(a)
    ep = 0.01*cv2.arcLength(c,True)  # cal.the max.len of arc of area of contour.
    d =  cv2.approxPolyDP(c,ep,True)    # plot the above detail.
    h = cv2.convexHull(d) # make the convex hull
# 4 points are needed for convex hull
    x,y,w,h = cv2.boundingRect(h)
    cv2.rectangle(img,(x,y),(x+w,y+w),(0,255,0),5)

print(ar)
cv2.imshow("thre",thr)
cv2.imshow("willma",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[358801.0, 29735.5, 26761.5, 12945.0, 10552.0, 29390.5, 27172.5, 26769.5, 24289.5, 23790.0, 21526.0, 31349.0, 28900.0]


In [3]:
# object detection using contour.
def willma(x): # scaling pases from a parameter which passesfrom function which gives nothing.
    pass

cv2.namedWindow("prachi")
cv2.createTrackbar("th","prachi",0,255,willma)

cv2.createTrackbar("lb","prachi",0,255,willma)
cv2.createTrackbar("lg","prachi",0,255,wQillma)
cv2.createTrackbar("lr","prachi",0,255,willma)

cv2.createTrackbar("hb","prachi",255,255,willma)
cv2.createTrackbar("hg","prachi",255,255,willma)
cv2.createTrackbar("hr","prachi",255,255,willma)

cap = cv2.VideoCapture(0)
while cap.isOpened():
    r,frame = cap.read()
    if r == True:

        thr = cv2.getTrackbarPos("th","prachi")

        LB = cv2.getTrackbarPos("lb","prachi")
        LG = cv2.getTrackbarPos("lg","prachi")
        LR = cv2.getTrackbarPos("lr","prachi")

        HB = cv2.getTrackbarPos("hb","prachi")
        HG = cv2.getTrackbarPos("hg","prachi")
        HR = cv2.getTrackbarPos("hr","prachi")

        lower = np.array([LB,LG,LR])
        upper = np.array([HB,HG,HR])

        
        frame = cv2.flip(frame,1)   # flip towards y- axis.
        frame = cv2.resize(frame,(400,400))
        hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)

        m = cv2.inRange(hsv,lower,upper)
        result = cv2.bitwise_and(frame,frame,mask = m)
        fr = cv2.bitwise_not(result)

        _,thi = cv2.threshold(m,thr,255,cv2.THRESH_BINARY)
        contour,hr = cv2.findContours(thi,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

        cv2.drawContours(frame,contour,-1,(255,0,0),2)

                            
        cv2.imshow("thr",thi)
        cv2.imshow("res",result)
        cv2.imshow("mask",m)
       # cv2.imshow("hsv",hsv)
        cv2.imshow("wc",frame)
        if cv2.waitKey(25) & 0xff == ord("q"):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()


In [5]:
# image background removal histogram

img = cv2.imread("img2.jpg")
img = cv2.resize(img,(500,500))
hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)    # TO CONVERT THE IMAGE IN HSV TYPE.

img1 = cv2.imread("img56.jpg")
hsv2 = cv2.cvtColor(img1,cv2.COLOR_BGR2HSV)

hist =cv2.calcHist([hsv2],[0,1],None,[180,256],[0,150,0,256],) # passing all chanel,x-axis,y-axis.
# img,channels,mask,histsize,ranges
mask = cv2.calcBackProject([hsv],[0,1],hist,[0,150,0,256],1)  # scale


ker = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))  # TO BUILD FILTER.
# SHAPE,KSIZE
mask = cv2.filter2D(mask,-1,ker)  # src,depth,kernel

boolean,thr = cv2.threshold(mask,230,255,cv2.THRESH_BINARY)   # CONVERT INTO BINARY IMAGE.
# src,thresh value,max. value,type

mask = cv2.merge((mask,mask,mask))

res = cv2.bitwise_or(img,mask)

cv2.imshow("willmajeet",res)
cv2.imshow("willmajeet1",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# hough transformation lines.  ( to build lines over images)
img = cv2.imread("img90.png")
gry = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

edg = cv2.Canny(gry,20,250)  # img, threshold1, 2  to detect edge

lines = cv2.HoughLinesP(edg , 1 ,np.pi/180 , 200 , minLineLength=50 , maxLineGap=10)
if lines is not None:
   for r,th in lines[0]:
       a = np.cos(th)    
       b = np.sin(th)

       x0 = a*r
       y0 = b*r

       x1 = int(x0+1000*(-b))
       y1 = int(y0+1000*(a))
       x2 = int(x0-1000*(-b))
       y2 = int(y0-1000*(a))

       cv2.line(img,(x1,y1),(x2,y2),(0,255,0))
else:
    print("no lines were detected")
    
cv2.imshow("willma",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

no lines were detected


In [ ]:
img = cv2.imread("img90.png")
gry = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

edg = cv2.Canny(gry, 20, 250)  # Perform Canny edge detection

# Use HoughLinesP for probabilistic line detection
lines = cv2.HoughLinesP(edg, 1, np.pi / 180, 100, minLineLength=50, maxLineGap=10)
print(lines)
if lines is not None:
    for line in lines:
        x1, y1, x2, y2 = line[0]
        cv2.line(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
else:
    print("No lines were detected.")

cv2.imshow("willma", img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
# template matching using opencv
img = cv2.imread("img100.jpg")
gry = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

tmp = cv2.imread("img101.jpg")
gry1 = cv2.cvtColor(tmp,cv2.COLOR_BGR2GRAY)

#print(gry1.shape)
w,h = gry1.shape[::-1]  #to use all rows and columns of the gray1 img.

res = cv2.matchTemplate(gry,gry1,cv2.TM_CCORR_NORMED) # TO MATCH THE SMALL IMG FROM BIGGER ONE.

thr = 0.99

l = np.where(res>=thr) #  to get gry1 img. in img. and outlined by a certain shape.
#print(l)  #array of our tmp has got.
for i in zip(*l[::-1]):
    cv2.rectangle(img,i,(i[0]+w,i[1]+h),(0,0,255),2) # img,pt1,pt2,colour,thickness


#print(res) # print points of dark blur img.
img = cv2.resize(img,(600,500))
#cv2.imshow("willma2",res)
cv2.imshow("willma",img)
cv2.imshow("willma1",tmp)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [15]:

w,h = gry1.shape[::-1]
w,h

(313, 348)

In [67]:
# Hough cicle detection.
img = cv2.imread("img103.jpeg")
gr = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
gr = cv2.medianBlur(gr,5) # kernelsize

c = cv2.HoughCircles(gr,cv2.HOUGH_GRADIENT,1,20,param1=80, param2=34,minRadius=0, maxRadius=0)
#(image, method, dp, minDist[, circles[, param1[, param2[, minRadius[, maxRadius
print(c)

data = np.uint16(np.around(c))  # roundfigure all data of circle.

for (x,y,r) in data[0,:]:
    cv2.circle(img,(x,y),r,(0,0,255),4)
#(img, center, radius, color[, thickness[, lineType



cv2.imshow("willma",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[[238.5 132.5  34.4]
  [ 89.5 121.5  33.6]
  [123.5  90.5  31.1]
  [100.5  54.5  27.7]
  [173.5 114.5  32. ]
  [197.5  29.5  25.8]
  [ 27.5  96.5  29.4]
  [235.5  72.5  30.7]
  [174.5  53.5  49. ]
  [ 51.5  70.5  34.3]
  [ 74.5  68.5  25.2]]]


In [21]:
# grabcut algorithm for background change.  ( remove background)
img = cv2.imread("img110.jpeg")

mask1 = np.zeros(img.shape[:2],np.uint8)

bgmask = np.zeros((1,65),np.float64)*255
fgmask = np.zeros((1,65),np.float64)*255

# x1,y1,x2,y2.
r = [24,16,251,173]
cv2.grabCut(img,mask1,r,bgmask,fgmask,10,cv2.GC_INIT_WITH_RECT)
#(img, mask, rect, bgdModel, fgdModel, iterCount[, mode]) -> mask, bgdModel, fgdModel

mask2 = np.where((mask1 ==2)|(mask1 == 0),0,1).astype("uint8")

img = img*mask2[:,:,np.newaxis] 


cv2.imshow("wilma",img)
cv2.waitKey(0)
cv2.destroyAllWindows()











In [37]:
# video background removal using algo.
cap = cv2.VideoCapture(r"C:\Users\HP LAPTOP-PC\Desktop\DRDO Project\running.mp4")

algo1 = cv2.createBackgroundSubtractorKNN(detectShadows = True)
algo2 = cv2.createBackgroundSubtractorMOG2(detectShadows = True)

while True:
    r,f = cap.read()
    if r == True:
        f = cv2.resize(f,(500,500))
        r1 = algo1.apply(f)
        r2 = algo2.apply(f)
        cv2.imshow("algo1",r1)
        cv2.imshow("algo2",r2)
        cv2.imshow("willma",f)
        if cv2.waitKey(40) & 0xff == ord("p"):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()

In [90]:
# object tracking and detection.
cap =cv2.VideoCapture(r"C:\Users\HP LAPTOP-PC\Desktop\video2.mp4")

# ROI PORTION
r,f = cap.read() # capture image from video
x,y,w,h = 130, 110, 510, 900# 4 coordinates of image 
t = (x,y,w,h)  # ROI
roi = f[y:y+h,x:x+w]  # to extract region of interest of image from video
hsv_roi = cv2.cvtColor(roi,cv2.COLOR_BGR2HSV) # convert frame in hsv format
mask = cv2.inRange(hsv_roi,np.array((0.,60.,32.)),np.array((180.,255.,255.)))
#(src, lowerb, upperb[, dst])
roi_hist = cv2.calcHist([hsv_roi],[0],mask,[180],[0,180]) # mask applied over histogram which filter it to get the image.
cv2.normalize(roi_hist,roi_hist,0,255,cv2.NORM_MINMAX)  # to normalize the data.
#(src, dst[, alpha[, beta[, norm_type[, dtype[, mask]]]]])
cv2.imshow("willma",roi)

# to implement roi on real video.
tr = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT,10,1)




while cap.isOpened():
    r,f = cap.read()
    if r == True:
        f = cv2.resize(f,(500,500))
        hsv_f = cv2.cvtColor(f,cv2.COLOR_BGR2HSV)
        d = cv2.calcBackProject([hsv_f],[0],roi_hist,[0,180],1)  # roi img overlapped with frames of video then search for roi img in video .
        boolean,tracking = cv2.meanShift(d,t,tr)  # shift the roi images according to the position in the video.
        #boolean,tracking = cv2.CamShift(d,t,tr) 
        # probImage, window, criteria
        x,y,w,h = tracking # new coordinates of image where it moves.
        final = cv2.rectangle(f,(x,y),(x+w,y+h),(0,0,255),4)
        cv2.imshow("willma",final)
        if cv2.waitKey(25) & 0xff == ord("q"):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()